### ISSUE TITLE
Refactor sitemap linking

### ISSUE THREAD

**Issue by choffmeister** [ePages-de/epages-docs#18]
Current format:

``` yaml
- key: themes
  title: Themes
  entries:
    - page: themes-getting-started
    - link:
        title: Use cases
        url: '/epages-docs/pages/apps/getting-started.html#use-cases'
```

Since links can already be written as `page:key#hash`, we should also align the sitemap so that the example from above would look like this:

``` yaml
- key: themes
  title: Themes
  entries:
    - page: 'themes-getting-started'
    - page: 'apps-getting-started#use-cases'
```
